Support multiple arguments in _scrape_posts_page
This is to fix the error:

TypeError: _scrape_posts_page() got an unexpected keyword
argument 'fallback'

Since scrape_posts accepts **kwargs and **kwargs are passed from there
to _scrape_posts_page, it seems logical
that that function needs to accept all
parameters as well.